Make Lottery Program
cleanios/TDD-Lottery-Hyunah pull request #1
Opened 2019-04-03 16:13 UTC by hyunable

## Issue Type
- feature

## description
- 로또 프로그램을 TDD 방식으로 만든다 

## 관련링크
[자바지기 - TDD 과제](https://www.slipp.net/questions/590)

2019-04-03 16:26 UTC, clsoft commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +        print("\(inputMoney)개를 구매했습니다.")
문맥상 self.inputMoney가 아니라 self.numberOfLotto가 들어가야 할 것 같습니다.

2019-04-03 16:57 UTC, clsoft commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +    func getOneLotto() -> Lotto {
side effect 없는 메서드는 명사구로 읽혀야 하며,
side effect 없이 값을 리턴하는 메서드에 get을 붙이는 것은 Swift API Design Guidelines 위배입니다.
코코아 터치 프레임워크에서 get으로 시작하는 메서드는 전부 completion handler를 받는 비동기 작업뿐인 것으로 알고 있습니다.

쭉 보니 LottoStore class의 get으로 시작하는 메서드들은 전부 side effect가 없는 것 같습니다.
전부 명사구로 바꿔주면 좋을 것 같습니다.

2019-04-03 17:00 UTC, clsoft commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +    func getLottos() -> [Lotto] {
side effect 없는 메서드는 명사구로 읽혀야 하며,
side effect 없이 값을 리턴하는 메서드에 get을 붙이는 것은 Swift API Design Guidelines 위배입니다.
코코아 터치 프레임워크에서 get으로 시작하는 메서드는 전부 completion handler를 받는 비동기 작업뿐인 것으로 알고 있습니다.

쭉 보니 LottoStore class의 get으로 시작하는 메서드들은 전부 side effect가 없는 것 같습니다.
전부 명사구로 바꿔주면 좋을 것 같습니다.

2019-04-03 17:29 UTC, clsoft commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +}
전체적으로 봤을 때,
인스턴스 변수와 메서드 앞에 self의 유무가 일관성이 없는 것 같습니다.

창기님은 self를 붙이는 걸 선호하시고(실제 창기님이 리드하는 프로젝트에서는 아예 컨벤션인 것으로 알고 있습니다.),
수진님은 self를 붙이지 않는 걸 선호하는 것처럼 개발자의 취향이지만 self가 있든지 없던지 일관되어야 좋을 것 같습니다.

2019-04-03 17:55 UTC, clsoft commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +                number = Int(arc4random_uniform(46))
Int.random(in:)를 써보는 건 어떨까요?

2019-04-03 17:55 UTC, clsoft commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +                number = Int(arc4random_uniform(46))
Int.random(in:)을 써보는 건 어떨까요?

2019-04-03 18:16 UTC, clsoft commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +    }
같은 기능을 하는 getter 메서드와 computed property가 둘 다 있어야 할 이유가 있나요?

2019-04-04 07:38 UTC, clsoft commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +    func getLottos() -> [Lotto] {
공식 문서: https://swift.org/documentation/api-design-guidelines/
번역본: https://minsone.github.io/swift-internals/api-design-guidelines/

2019-04-04 08:27 UTC, gbmksquare requested changes

2019-04-04 08:27 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDD/ViewController.swift
> +        let _ = lottoStore.getTotalRank(lottos: lottos)
@discardableResult 를  써보세요

2019-04-04 08:27 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDDTests/LottoStoreTests.swift
> +//
유닛테스트 컴파일이 안되니 확인해주세요

2019-04-04 08:27 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +//
파일 하나에 모든 것이 있으니 가독성이 떨어지고 구조 파악이 힘듭니다. 좀 더 클래스와  파일을 분리해주시면 좋을 것 같습니다.

2019-04-04 08:27 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +//* 기능 요구사항
구현 내용을 커멘트로 남긴 것은 좋습니다 👍

2019-04-04 08:27 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +class LottoStore {
로또 상점인지 로또 저장소인지 헷갈릴 수 있는 여지가 있어 보입니다.

2019-04-04 08:27 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +    var numberOfLotto: Int {
밑에 `lottos`를 사용하니 여기서도 `numberOfLottos`로 사용하는 것이 좋을거 같네요.

2019-04-06 02:14 UTC, hyunable commented on 1st_LottoTDD/LottoTDDTests/LottoStoreTests.swift
> +//
픽스해서 다시 푸쉬했습니다 :)

2019-04-06 02:14 UTC, hyunable commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +        print("\(inputMoney)개를 구매했습니다.")
엇 그렇네요! 세심하게 잡아주셔서 감사합니다 💯

2019-04-06 02:14 UTC, hyunable commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +    func getLottos() -> [Lotto] {
넘나 좋은 지적 감사합니다! 공식 문서를 보고 네이밍 공부를 해야겠네요 👍

2019-04-06 02:44 UTC, hyunable commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +}
네! 그러는게 좋겠네요 ㅎㅎ (그럼 창기님스타일로 통일..?)

2019-04-06 03:17 UTC, hyunable commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +    }
외부에서 접근시 함수를 직접 호출하기 보단 함수는 private로 내부접근으로하고 가공된 결과만 internal 변수로 접근하게끔 하려고 한것인데 ..음.. `getLottos` 도 private으로 안되어있네요 ㅋㅋㅋ 
다른 사이드이펙트 없이 발행된 로또만 제공하므로 `getLottos` 는 직접 호출해도 괜찮을것 같습니다!

2019-04-06 03:28 UTC, hyunable commented on 1st_LottoTDD/LottoTDD/ViewController.swift
> +        let _ = lottoStore.getTotalRank(lottos: lottos)
오옷! 너무 좋은 팁 감사합니다 👍

2019-04-06 03:29 UTC, hyunable commented on 1st_LottoTDD/LottoTDD/LottoStore.swift
> +class LottoStore {
그러네요! 네임을 변경할 필요가 있어보입니다.

2019-04-08 01:07 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDDTests/LottoShopTests.swift
> +    func testpublishedLotto() {
🐫

2019-04-08 01:07 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDDTests/LottoShopTests.swift
> +    func testpublishedLotto_ShouldNotHaveZero() {
🐫

2019-04-08 01:07 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDDTests/LottoShopTests.swift
> +        lottoShop = LottoShop(money: 4000)
`setup()`에서 `lottoShop`을 만들었는데 아래 테스트에서 사용하지 않고 있네요.

2019-04-08 01:07 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDDTests/LottoShopTests.swift
> +        let lottoShop = LottoShop(money: 4000)
딱 1000의 배수가 아닌 구매액에 대한 테스트가 부족해 보이네요.

2019-04-08 01:07 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDD/LottoResult.swift
> +    static func totalRankOfLotto(lottos: [Lotto]) -> [Int] {
하나의 로또의 결과를 알려주는 메서드를 별도로 분리하는게 어떨까요?

2019-04-08 01:07 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDD/LottoResult.swift
> +    static func totalRankOfLotto(lottos: [Lotto]) -> [Int] {
이름은 `rankings(for lottos: [Lotto]) -> [Int]` 정도로 줄일 수 있겠네요.

2019-04-08 01:07 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDDTests/LottoResultTests.swift
> +    // ** 당첨숫자  16, 20, 24, 28, 36, 39 , bonus: 5
당첨 숫자가 미리 정해졌있다면 테스트의 유효성이 줄어들지 않을까요?

2019-04-08 01:07 UTC, gbmksquare commented on 1st_LottoTDD/LottoTDDTests/LottoResultTests.swift
> +    func testrankOfLottoShoulReturnNumberOfSameNumberAndPrizes_for5thWinner() {
🐫🐪🐫🐪🐫🐪

2019-04-08 07:05 UTC, clsoft commented on 1st_LottoTDD/LottoTDDTests/LottoResultTests.swift
> +    // ** 당첨숫자  16, 20, 24, 28, 36, 39 , bonus: 5
좋은 지적이네요.
저도 이 코멘트를 읽고서 당첨 번호를 랜덤으로 생성되도록 수정하였습니다.

2019-04-08 07:06 UTC, clsoft commented on 1st_LottoTDD/LottoTDDTests/LottoResultTests.swift
> +    // ** 당첨숫자  16, 20, 24, 28, 36, 39 , bonus: 5
좋은 지적이네요.
저도 이 코멘트를 읽고서 당첨 번호가 랜덤으로 생성되도록 수정하였습니다.

2019-04-08 07:47 UTC, clsoft commented on 1st_LottoTDD/LottoTDDTests/LottoShopTests.swift
> +        let lottoShop = LottoShop(money: 4000)
1000의 배수가 아니더라도 명확하게 lottery price로 나누어서 계산하게 되는데,
굳이 money가 4300, 4320, 4321인 case에 대한 테스트가 작성되어야 할까요?
테스트의 최소 단위는 어떻게 정하는 것이 좋을까요?

테스트 코드 작성이 주는 가장 큰 이점이 기존 코드의 리팩토링 방향을 잡아주는 것이라고 생각하는데,
제 생각엔 그 방향을 잡을 수 있는 선에서 최소 단위를 수립하는 것이 좋을 것 같다고 생각했거든요.
그렇게 하지 않으면 테스트 코드 작성이 주는 이점보다는 시간적 기회비용이 낭비되는 것은 아닐까요?

이 테스트에서 1000의 배수가 아닌 구매액에 대한 테스트 케이스를 작성하면 이전보다는 세세하게 결과의 동작에 대해서 보장한다고 말할 수 있지만,
작성된 테스트 케이스에 의해 lottery price로 나누어서 계산하는 로직에 대한 코드가 더 나은 코드로 리팩토링 될 것이라는 생각이 들지 않습니다.

이건 제가 여러분들의 의견이 궁금해서 코멘트를 남겨봅니다.

2019-04-16 20:50 UTC, hyunable commented on 1st_LottoTDD/LottoTDDTests/LottoShopTests.swift
> +        lottoShop = LottoShop(money: 4000)
이니셜라이져에서만 생성해서 쓰고 다른부분에서는 만들어둔 `lottoShop`을 쓰려고 했는데 쓰질않았네요.
사용하는 것으로 적용하였습니다!

2019-04-16 20:52 UTC, hyunable commented on 1st_LottoTDD/LottoTDD/LottoResult.swift
> +    static func totalRankOfLotto(lottos: [Lotto]) -> [Int] {
위에 `rankOfLotto` 가 하나의 결과를 알려주는 메서드로 분리되어있습니다. :) 다시 한번 확인부탁드립니다.

2019-04-16 20:58 UTC, hyunable commented on 1st_LottoTDD/LottoTDD/LottoResult.swift
> +    static func totalRankOfLotto(lottos: [Lotto]) -> [Int] {
어법상 `rank + target`으로 전치사 없이 쓰이므로` rankings(lottos: [Lotto]) -> [Int]` 로 쓰는 건 어떨가요?

2019-04-16 21:02 UTC, hyunable commented
@clsoft , @gbmksquare 리뷰적용되었습니다.  리뷰 후 머지 ;ㅅ; 부탁드립니다아아

2019-04-17 07:03 UTC, clsoft approved these changes

2019-04-17 07:48 UTC, gbmksquare approved these changes

2019-04-17 20:25 UTC, merged